version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGITActionsProject
  gitServerName: testNewgit
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testgitactions.integrations:a2
  packages:
  - name: TestGITActionsProject
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.1962
